In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("C:\\Users\\Shubhi\\MACHINE LEARNING\\diabetes.csv")

In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df = df.drop("Pregnancies", axis=1)

In [6]:
df.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,148,72,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,32,1
3,89,66,23,94,28.1,0.167,21,0
4,137,40,35,168,43.1,2.288,33,1

In [7]:
import matplotlib.pyplot as plt

In [8]:
import sklearn
print(sklearn.__version__)

1.8.0

In [9]:
X= df.iloc[: ,0:7]
Y= df.iloc[: ,-1]

In [10]:
X

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,148,72,35,0,33.6,0.627,50
1,85,66,29,0,26.6,0.351,31
2,183,64,0,0,23.3,0.672,32
3,89,66,23,94,28.1,0.167,21
4,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...
763,101,76,48,180,32.9,0.171,63
764,122,70,27,0,36.8,0.340,27
765,121,72,23,112,26.2,0.245,30
766,126,60,0,0,30.1,0.349,47
767,93,70,31,0,30.4,0.315,23

In [11]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
X.shape

(768, 7)

In [13]:
Y.shape

(768,)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2)

In [15]:
X_train

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
606,181,78,42,293,40.0,1.258,22
463,88,78,30,0,27.6,0.258,37
390,100,66,29,196,32.0,0.444,42
382,109,60,8,182,25.4,0.947,21
122,107,74,30,100,33.6,0.404,23
...,...,...,...,...,...,...,...
758,106,76,0,0,37.5,0.197,26
674,91,82,0,0,35.6,0.587,68
607,92,62,25,41,19.5,0.482,25
329,105,70,32,68,30.8,0.122,37
303,115,98,0,0,52.9,0.209,28

In [16]:
Y_train

606    1
463    0
390    0
382    0
122    0
      ..
758    0
674    0
607    0
329    0
303    1
Name: Outcome, Length: 614, dtype: int64

In [17]:
X_test

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
383,90,62,18,59,25.1,1.268,25
155,152,88,44,0,50.0,0.337,36
300,167,0,0,0,32.3,0.839,30
490,83,65,28,66,36.8,0.629,24
759,190,92,0,0,35.5,0.278,66
...,...,...,...,...,...,...,...
96,92,62,28,0,31.6,0.130,24
195,158,84,41,210,39.4,0.395,29
560,125,76,0,0,33.8,0.121,54
641,128,70,0,0,34.3,0.303,24
639,100,74,12,46,19.5,0.149,28

In [18]:
Y_test

383    0
155    1
300    1
490    0
759    1
      ..
96     0
195    1
560    1
641    0
639    0
Name: Outcome, Length: 154, dtype: int64

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)

In [21]:
X_train

array([[ 1.89543409,  0.43899846,  1.38014285, ...,  1.00679823,
         2.45918414, -0.95526842],
       [-1.04081499,  0.43899846,  0.61000558, ..., -0.57714999,
        -0.66590317,  0.29144012],
       [-0.66194414, -0.1755827 ,  0.54582747, ..., -0.01510385,
        -0.08463693,  0.70700963],
       ...,
       [-0.91452471, -0.38044309,  0.28911505, ..., -1.61182584,
         0.03411638, -0.70592671],
       [-0.50408129,  0.02927769,  0.73836179, ..., -0.16838916,
        -1.09091505,  0.29144012],
       [-0.18835558,  1.4633004 , -1.3153376 , ...,  2.65461533,
        -0.81903245, -0.45658501]], shape=(614, 7))

In [45]:
X_test= scaler.transform(X_test)

C:\Users\Shubhi\anaconda3\envs\new_environment\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [46]:
X_test

array([[ -3.76197907,  -3.85552938,  -1.26609947, ...,  -4.40549436,
         10.67865613,  -3.36622245],
       [ -3.7602598 ,  -3.85145141,  -1.26108017, ...,  -4.35789922,
         -7.38473981,  -3.35673791],
       [ -3.75984385,  -3.86525377,  -1.26957437, ...,  -4.39173191,
          2.35513641,  -3.3619113 ],
       ...,
       [ -3.76100852,  -3.85333355,  -1.26957437, ...,  -4.38886473,
        -11.57560288,  -3.34121775],
       [ -3.76092533,  -3.85427462,  -1.26957437, ...,  -4.38790901,
         -8.0444127 ,  -3.36708468],
       [ -3.76170177,  -3.85364724,  -1.26725777, ...,  -4.41619849,
        -11.03234285,  -3.36363576]], shape=(154, 7))

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
clf= LogisticRegression()

In [49]:
clf.fit(X_train, Y_train)

LogisticRegression()

In [50]:
clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
Y_pred = clf.predict(X_test)
accuracy_score(Y_test, Y_pred)

0.6753246753246753

In [54]:
import pickle
pickle.dump(clf, open('model1.pkl', 'wb'))

In [55]:
print(clf.predict_proba(sample_scaled))

NameError: name 'sample_scaled' is not defined

In [56]:
print(clf.predict_proba(X_test))

[[9.96337825e-01 3.66217525e-03]
 [9.99963016e-01 3.69841831e-05]
 [9.99559470e-01 4.40530109e-04]
 [9.99845179e-01 1.54821441e-04]
 [9.99972708e-01 2.72924520e-05]
 [9.99205778e-01 7.94221698e-04]
 [9.99976900e-01 2.30997052e-05]
 [9.99982611e-01 1.73885303e-05]
 [9.99986115e-01 1.38854339e-05]
 [9.99942400e-01 5.76002569e-05]
 [9.99526978e-01 4.73021899e-04]
 [9.99175539e-01 8.24461036e-04]
 [9.99935607e-01 6.43927599e-05]
 [9.99946696e-01 5.33038245e-05]
 [9.99963603e-01 3.63967744e-05]
 [9.99578398e-01 4.21601733e-04]
 [9.99972869e-01 2.71312398e-05]
 [9.99912680e-01 8.73196613e-05]
 [9.99898647e-01 1.01352666e-04]
 [9.99984674e-01 1.53257102e-05]
 [9.99965557e-01 3.44434057e-05]
 [9.99968735e-01 3.12648639e-05]
 [9.99958978e-01 4.10219759e-05]
 [9.93209531e-01 6.79046858e-03]
 [9.99867497e-01 1.32502539e-04]
 [9.99987071e-01 1.29293113e-05]
 [9.99909180e-01 9.08200675e-05]
 [9.99974139e-01 2.58609848e-05]
 [9.89714882e-01 1.02851184e-02]
 [9.99829415e-01 1.70585136e-04]
 [9.99963452e-01 3.65483822e-05]
 [9.99964129e-01 3.58709233e-05]
 [9.99982091e-01 1.79090932e-05]
 [9.92887258e-01 7.11274213e-03]
 [9.99887930e-01 1.12069870e-04]
 [9.99899512e-01 1.00488091e-04]
 [9.99345899e-01 6.54100894e-04]
 [9.99876081e-01 1.23919192e-04]
 [9.99747341e-01 2.52658799e-04]
 [9.99985850e-01 1.41499782e-05]
 [9.99981908e-01 1.80924627e-05]
 [9.99981988e-01 1.80122837e-05]
 [7.78898335e-01 2.21101665e-01]
 [9.99987416e-01 1.25844168e-05]
 [9.99970466e-01 2.95341905e-05]
 [9.99891008e-01 1.08992323e-04]
 [9.99970936e-01 2.90640670e-05]
 [9.99942116e-01 5.78840151e-05]
 [9.99733536e-01 2.66463667e-04]
 [9.99938573e-01 6.14268066e-05]
 [9.99980122e-01 1.98784426e-05]
 [9.99877199e-01 1.22800561e-04]
 [9.99983629e-01 1.63705733e-05]
 [9.99830185e-01 1.69815005e-04]
 [9.99170435e-01 8.29564600e-04]
 [9.99952729e-01 4.72711145e-05]
 [9.99987468e-01 1.25316053e-05]
 [9.65571964e-01 3.44280357e-02]
 [9.99961513e-01 3.84873618e-05]
 [9.99975104e-01 2.48964247e-05]
 [9.99989901e-01 1.00985661e-05]
 [9.99987749e-01 1.22509255e-05]
 [9.99987962e-01 1.20382986e-05]
 [9.99951121e-01 4.88785575e-05]
 [9.99973959e-01 2.60406398e-05]
 [9.99981849e-01 1.81509192e-05]
 [9.99986113e-01 1.38872447e-05]
 [9.99974467e-01 2.55331718e-05]
 [9.99770760e-01 2.29240224e-04]
 [9.99982840e-01 1.71597874e-05]
 [9.99981224e-01 1.87763724e-05]
 [9.99989819e-01 1.01811631e-05]
 [9.99973835e-01 2.61653648e-05]
 [9.99975594e-01 2.44059575e-05]
 [9.99979761e-01 2.02392377e-05]
 [9.99976512e-01 2.34876577e-05]
 [9.99744454e-01 2.55545550e-04]
 [9.99985281e-01 1.47185637e-05]
 [9.99983111e-01 1.68889376e-05]
 [9.99762068e-01 2.37931769e-04]
 [9.99976168e-01 2.38317668e-05]
 [9.99986851e-01 1.31488864e-05]
 [9.99750718e-01 2.49282038e-04]
 [9.99974635e-01 2.53646910e-05]
 [9.99986302e-01 1.36975269e-05]
 [9.99837987e-01 1.62012613e-04]
 [9.99970690e-01 2.93100183e-05]
 [9.99920289e-01 7.97110664e-05]
 [4.55602228e-01 5.44397772e-01]
 [9.99777354e-01 2.22645970e-04]
 [9.99925112e-01 7.48883837e-05]
 [9.99880370e-01 1.19630374e-04]
 [9.99697052e-01 3.02948245e-04]
 [9.99988641e-01 1.13587386e-05]
 [9.99935599e-01 6.44013628e-05]
 [9.99986686e-01 1.33141694e-05]
 [9.99988988e-01 1.10123685e-05]
 [9.99969032e-01 3.09682079e-05]
 [9.99971281e-01 2.87190443e-05]
 [9.99894963e-01 1.05037165e-04]
 [9.99791981e-01 2.08019233e-04]
 [9.99988166e-01 1.18342426e-05]
 [9.99970528e-01 2.94719359e-05]
 [9.99948150e-01 5.18504899e-05]
 [9.99948886e-01 5.11143014e-05]
 [9.99189169e-01 8.10831120e-04]
 [9.99892472e-01 1.07528394e-04]
 [9.99977953e-01 2.20468393e-05]
 [9.99787801e-01 2.12198511e-04]
 [9.99974082e-01 2.59179757e-05]
 [9.99219713e-01 7.80287307e-04]
 [9.99956237e-01 4.37626528e-05]
 [9.98146839e-01 1.85316108e-03]
 [9.99977378e-01 2.26224136e-05]
 [9.99963708e-01 3.62919446e-05]
 [9.99962413e-01 3.75865324e-05]
 [9.99971911e-01 2.80893147e-05]
 [9.99955483e-01 4.45167076e-05]
 [9.99968288e-01 3.17123818e-05]
 [9.99819741e-01 1.80259002e-04]
 [9.99981638e-01 1.83615092e-05]
 [9.99945337e-01 5.46634854e-05]
 [9.99705880e-01 2.94119739e-04]
 [9.99981416e-01 1.85837775e-05]
 [9.99965334e-01 3.46656320e-05]
 [9.99974922e-01 2.50777517e-05]
 [9.99971430e-01 2.85704297e-05]
 [9.99980538e-01 1.94623007e-05]
 [9.99985002e-01 1.49977188e-05]
 [9.99985689e-01 1.43105391e-05]
 [9.99978601e-01 2.13992413e-05]
 [9.99908924e-01 9.10764083e-05]
 [9.95278935e-01 4.72106458e-03]
 [9.99825621e-01 1.74378882e-04]
 [9.99949838e-01 5.01615238e-05]
 [9.99920578e-01 7.94223833e-05]
 [9.99757864e-01 2.42135858e-04]
 [9.99860066e-01 1.39934019e-04]
 [9.99974665e-01 2.53352965e-05]
 [9.99978844e-01 2.11559805e-05]
 [9.99586126e-01 4.13873624e-04]
 [9.99805978e-01 1.94022137e-04]
 [9.98556315e-01 1.44368523e-03]
 [9.99973862e-01 2.61383451e-05]
 [9.99971661e-01 2.83391641e-05]
 [9.99740292e-01 2.59708437e-04]
 [9.99932235e-01 6.77645198e-05]
 [9.99948185e-01 5.18154433e-05]
 [9.99949548e-01 5.04520129e-05]
 [9.99987178e-01 1.28218936e-05]
 [9.99951395e-01 4.86049665e-05]
 [9.99987598e-01 1.24016260e-05]
 [9.99969522e-01 3.04775426e-05]
 [9.99986116e-01 1.38838141e-05]]

In [57]:
scaler = pickle.load(open('scaler.pkl', 'rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'scaler.pkl'

In [58]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))